# Generated by Django 2.0.5 on 2018-10-13 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20181012_1827'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='books',
            name='features',
            field=models.TextField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='books',
            name='image',
            field=models.ImageField(blank=True, upload_to='products/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='books',
            name='isbn_no',
            field=models.TextField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='books',
            name='level',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='books',
            name='series',
            field=models.TextField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='books',
            name='type',
            field=models.IntegerField(choices=[(1, 'Books'), (2, 'Video')], default=1),
        ),
        migrations.AddField(
            model_name='books',
            name='category',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='books', to='books.Category'),
        ),
    ]
