# Generated by Django 2.0.5 on 2018-10-14 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20181013_1943'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='type',
            new_name='book_type',
        ),
    ]
