# Generated by Django 2.0.5 on 2018-10-25 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_auto_20181017_1008'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='books',
            options={'ordering': ('-title',)},
        ),
        migrations.AddField(
            model_name='books',
            name='slug',
            field=models.SlugField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
        migrations.AlterIndexTogether(
            name='books',
            index_together={('id', 'slug')},
        ),
    ]
