# Generated by Django 2.0.5 on 2018-11-16 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_auto_20181107_0911'),
    ]

    operations = [
        migrations.CreateModel(
            name='CenterContentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('discription', models.TextField(max_length=250)),
                ('call_to_action_value', models.URLField()),
                ('image', models.ImageField(blank=True, upload_to='products/%Y/%m/%d')),
                ('html_content', models.TextField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='MarketingContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('html_content', models.TextField(max_length=250)),
                ('image', models.ImageField(blank=True, upload_to='products/%Y/%m/%d')),
                ('sequence_no', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ScrollAbleContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('html_content', models.TextField(max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='books',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Title'),
        ),
    ]
