# Generated by Django 2.0.5 on 2018-11-22 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0015_books_ating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='ating',
            new_name='rating',
        ),
    ]
